### PR TITLE
Add configuration to disable either feature

### PR DESCRIPTION
**Pull request by sleepingdragoninn**
Implements #2 - very much just adds the two booleans and a few if statements!

Tested on 1.19.2 and seems to work fine.

### CODE REVIEW

**Comment by fantahund** [comment]
Have you ever tested it on a server?
https://fantacs.de/Dutchsmoushond1703.png

**Comment by fantahund** [comment]
It will be difficult to implement this. The server does not tell the client its current settings.

**Comment by sleepingdragoninn** [comment]
oh we can add the networking for that, no sweat, be up in under an hour.

**Comment by fantahund** [comment]
I'm already on it.

**Comment by fantahund** [comment]
I'm about to rebuild a little bit the config things have bothered me for a long time in the mod.
https://github.com/fantahund/EasierEnchanting/tree/disablereroll

**Comment by sleepingdragoninn** [comment]
Ah all good then! I'll leave you to it.

**Comment by fantahund** [comment]
done https://modrinth.com/mod/easierenchanting/version/1.5.0

**Pull request merged**
